name: "Surikat Homeassistant"
description: "Surikat plugin for Homeassistant"
version: "1.0.1"
slug: "surikat"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
options:
  mqtt_host: "mqtt://localhost"
  mqtt_port: 1883
  mqtt_topic: "frigate/events"
  mqtt_user: "user"
  mqtt_password: "password"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_topic: str
  mqtt_user: str
  mqtt_password: str
environment:
  MQTT_HOST: !env_var mqtt_host
  MQTT_PORT: !env_var mqtt_port
  MQTT_TOPIC: !env_var mqtt_topic
  MQTT_USER: !env_var mqtt_user
  MQTT_PASSWORD: !env_var mqtt_password