name: "Surikat Homeassistant"
description: "Surikat plugin for Homeassistant"
version: "1.0.1"
slug: "surikat"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000